[defaults]
email = "test@example.com"
mx = {name = "mail.example.com.", prio = 10}
mx-prio = 40
nameserver = "ns1.example.com."

[reverse]
"10.0.1.0/24" = {}
"10.0.2.0/24" = {}
"10.0.3.0/24" = {}
"10.0.4.0/24" = {}
"fd00:1234:5678:1::/64" = {ttl = 10, nameserver = "ns2.example.com."}
"fd00:1234:5678:2::/64" = {email = "admin@example.com"}

[[zone]]
mx = "mail.example.com"
name = "unifi"
with-ptr = false
[zone.hosts]
unifi = {alias = "@", ip = "10.0.1.5"}

[[zone]]
email = "admin@example.com"
mx = {name = "mail", prio = 20}
name = "example.com"
nameserver = "ns1"
nrc-ttl = 300

[zone.hosts]
"*" = ["10.0.1.5", "fd00:1234:5678:1::5"]
backup = ["10.0.1.4", "fd00:1234:5678:1::4"]
db = "10.0.1.7"
docker = {alias = [
  "app1",
  "app2",
  "app3",
  "app4",
  "app5",
  "app6",
  "app7",
  "app8",
], ip = [
  "10.0.1.5",
  "fd00:1234:5678:1::5",
]}
gateway = ["203.0.113.10", "2001:db8:1::1"]
git = "10.0.1.6"
ldap = "10.0.1.9"
mail = ["10.0.1.20", "fd00:1234:5678:1::20"]
server1 = ["10.0.1.2", "fd00:1234:5678:1::2"]
mqtt = "10.0.1.111"
server2 = ["10.0.1.3", "fd00:1234:5678:1::3"]
vault = "10.0.1.8"
router = {alias = [
  "@",
  "cups",
  "dns",
  "ns1",
  "ntp",
  "proxy",
  "time",
  "wpad",
  "www",
  "bookmarks",
], ip = [
  "10.0.1.1",
  "fd00:1234:5678:1::1",
]}

airprint = "10.0.1.12"
storage = ["10.0.1.11", "fd00:1234:5678:1::b"]
media = ["10.0.1.13", "fd00:1234:5678:1::13"]
rss = "10.0.1.16"
files = "10.0.1.14"

nas = {ip = ["10.0.1.17", "fd00:1234:5678:1::11"], ttl = 10}

music = "10.0.1.21"
bookmarks = "10.0.1.23"

homeassistant = "10.0.1.37"

apps = {alias = [
  "app9",
  "app10",
], ip = [
  "10.0.1.48",
  "fd00:1234:5678:1::30",
]}

printer = "10.0.1.200"

main_switch = "10.0.1.251"
switch0 = "10.0.1.249"
switch1 = "10.0.1.250"
ap0 = "10.0.1.253"
ap1 = "10.0.1.252"

[zone.srv]
"_caldavs._tcp" = {port = 443, target = "@"}
"_carddavs._tcp" = {port = 443, target = "@"}
"_mqtt._tcp" = {port = 1883, target = "mqtt"}
"_mqtts._tcp" = {port = 8883, target = "mqtt"}
"_secure-mqtt._tcp" = {port = 8883, target = "mqtt"}

[[zone]]
email = "admin@example.com"
mx = [{name = "mail.example.com.", prio = 10}]
name = "iot.example.com"
nameserver = ["ns1.example.com."]

hosts = {controller = "10.0.3.13", automation = "10.0.3.14", monitor = "10.0.3.15"}

[[zone]]
email = "admin@example.com"
name = "devices.example.com"
nameserver = "ns1.example.com."
[zone.mx]
name = "mail.example.com."
prio = 10
[zone.hosts]
time = {alias = "mqtt", ip = "10.0.4.1"}

sensor-01 = "10.0.4.25"
sensor-02 = "10.0.4.23"
sensor-03 = "10.0.4.24"
sensor-04 = "10.0.4.21"
sensor-05 = "10.0.4.20"
sensor-06 = "10.0.4.27"
sensor-07 = "10.0.4.22"
sensor-08 = "10.0.4.26"
sensor-09 = "10.0.4.28"

relay-01 = "10.0.4.31"
relay-02 = "10.0.4.32"
relay-03 = "10.0.4.30"

smoke-detector-01 = {ip = "10.0.4.40", ttl = 3600}

dimmer-01 = "10.0.4.50"

shutter-01 = "10.0.4.64"
shutter-02 = "10.0.4.63"
shutter-03 = "10.0.4.62"
shutter-04 = "10.0.4.61"
shutter-05 = "10.0.4.60"

plug-01 = "10.0.4.70"
plug-02 = "10.0.4.71"

input-module-01 = "10.0.4.80"
input-module-02 = "10.0.4.81"
[zone.cname]
thermostat-office = "plug-02"
light-office = "shutter-01"

[[zone]]
name = "cluster.example.com"
[zone.hosts]
node1 = ["10.0.2.2", "fd00:1234:5678:2::2"]
node2 = ["10.0.2.3", "fd00:1234:5678:2::3"]
node3 = ["10.0.2.4", "fd00:1234:5678:2::4"]
router = ["10.0.2.1", "fd00:1234:5678:2::1"]

appserver = {ip = ["10.0.2.69", "fd00:1234:5678:2::69"], ttl = 42}
gitserver = ["10.0.2.66", "fd00:1234:5678:2::66"]
mailserver = ["10.0.2.67", "fd00:1234:5678:2::67"]
chatserver = ["10.0.2.65", "fd00:1234:5678:2::65"]
videoserver = ["10.0.2.70", "fd00:1234:5678:2::70"]
dbserver = ["10.0.2.71", "fd00:1234:5678:2::71"]
webserver = ["10.0.2.68", "fd00:1234:5678:2::68"]
[zone.cname]
web = "router"
